services:
  tool-belt-db:
    image: postgres
    container_name: tool-belt-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432"
    networks:
      - eyad_default

  tool-belt-base:
    volumes:
      - ${PWD}:/app
    build:
      context: .
    container_name: tool-belt-base
    ports:
      - "80"

  tool-belt-service:
    extends:
      service: tool-belt-base
    container_name: tool-belt-service
    depends_on:
      - tool-belt-db
    command:
      [
        "gunicorn",
        "-c",
        "gunicorn_conf.py",
        "-b",
        "0.0.0.0:80",
        "src.main:app"
      ]

  tool-belt-alembic:
    extends:
      service: tool-belt-base
    depends_on:
      - tool-belt-db
    container_name: tool-belt-alembic
    command: [ "alembic", "upgrade", "head" ]
    # tool-belt-tests:
    #   container_name: tool-belt-tests
    #   extends:
    #     service: tool-belt-base
    #   ports:
    #     - "80:80"
    #   command:
    #     [
    #       "pytest",
    #       "-vvv",
    #       "--cov=src",
    #       "--cov-fail-under=90",
    #       "--cov-config=setup.cfg",
    #       "--cov-report",
    #       "term-missing",
    #       "tests"
    #     ]
networks:
  eyad_default:
    name: eyad_default
